name: Update Branches from Main

on:
  push:
    branches:
      - dev

env:
  DEPLOY_HOOK: ${{ vars.DEPLOY_HOOK }}

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to main-in branch
        env:
          SOURCE_BRANCH: dev
          DESTINATION_BRANCH: dev-in

        run: |
          git checkout $SOURCE_BRANCH
          git branch -f $DESTINATION_BRANCH $SOURCE_BRANCH
          git push --force origin $DESTINATION_BRANCH

  deploy:
    runs-on: ubuntu-latest
    needs: push
    environment: dev

    steps:
      - name: Deploy
        run: |
          curl ${{ env.DEPLOY_HOOK }}
