name: Update Branches from Main

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to main-in branch
        run: |
          git checkout main
          git branch -f main-in main
          git push --force origin main-in